### ISSUE TITLE
english version

### ISSUE THREAD

**Issue by jdgamble555** [HerbertHe/svelte-vditor-demo#1]
This is great! Would be cool if you had an English option during initialization.

J

**Comment by HerbertHe** [comment]
@jdgamble555 I've updated the readme in English, [here](https://github.com/HerbertHe/svelte-vditor-demo/blob/main/README.en.md)

**Comment by HerbertHe** [comment]
> This is great! Would be cool if you had an English option during initialization.
> 
> J

You mean the Vditor editor in English? See [options](https://github.com/Vanessa219/vditor/blob/master/README_en_US.md#options)

I've contributed the feature `i18n` for Vditor, you just need to set the value of `options.lang` as `en_US`.

**Comment by HerbertHe** [comment]
The second arg of the class `Vditor` is `options`.

```ts
new Vditor(`<id>`, { ...options })
```
